[build]
  functions = "netlify/functions"
  command = "npm install"

[[blobs]]
  name = "kva-pdfs"
  access = "public"

# 🔥 IMPORTANT (à ajouter)
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/favicon.png"
  to = "/favicon.png"
  status = 200

[[redirects]]
  from = "/kva-intro-loop.mp4"
  to = "/kva-intro-loop.mp4"
  status = 200

[[redirects]]
  from = "/signin"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/signin/"
  to = "/signin"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/site.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/site.html"
  status = 200
  force = true
